version: '3.6'

services:
    mysql:
        image: webbben/pids-ceoconnex-mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PASS}
        restart: always
        networks:
            - yourls_host
        volumes:
         - data_volume:/var/lib/mysql

    yourls:
        image: webbben/pids-geoconnex-yourls:latest
        environment:
            YOURLS_DB_PASS: ${SQL_ROOT_PASS}
            YOURLS_SITE: ${YOURLS_HOSTNAME}:${YOURLS_PORT}
            YOURLS_USER: ${YOURLS_USER}
            YOURLS_PASS: ${YOURLS_PASS}
            YOURLS_URL_CONVERT: ${YOURLS_URL_CONVERT}
            YOURLS_PRIVATE_API: "${YOURLS_PRIVATE_API}"
            YOURLS_UNIQUE_URLS: "${YOURLS_UNIQUE_URLS}"
        restart: always
        networks: 
            - yourls_host
        ports:
            - ${YOURLS_PORT}:80

networks:
    yourls_host:
volumes:
    data_volume:
