name: pid.geoconnex.us database build

on: [ push, pull_request ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build MySQL for Yourls
        run: |
          docker-compose up -d --build  
      - name: Populate Yourls table from namespaces
        run: |
          docker build -t build_yourls_uploader ./build/
          docker run --rm --network=pidsgeoconnexus_yourls_host --name build_yourls -v /sitemap:/sitemap -e "YOURLS_DB_PASS=arootpassword" build_yourls_uploader
      - name: Dump SQL backup from database
        run: |
          export 
          docker exec pidsgeoconnexus_mysql_1 sh -c "mysqldump -u root --password=arootpassword yourls | gzip > /yourls.sql.gz"
          docker cp pidsgeoconnexus_mysql_1:/yourls.sql.gz ./mysql/yourls.sql.gz
          cp /sitemap ./yourls/sitemap
      - name: Build and push geoconnex-mysql
        id: docker_build_mysql
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: webbben/pids-geoconnnex-mysql:latest
          context: mysql
      - name: Build and push geoconnex-yourls
        id: docker_build_yourls
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: webbben/pids-geoconnnex-yourls:latest
          context: yourls
      - name: Save SQL Artifact
        uses: actions/upload-artifact@v2
        with:
          name: yourls
          path: ./mysql
      - name: Save sitemap Artifact
        uses: actions/upload-artifact@v2
        with:
          name: sitemap
          path: /sitemap
