name: pid.geoconnex.us database build

on: 
  push:
    branches: 
      - 'main'
    paths:
      - 'namespaces/**'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Build MySQL for Yourls
        run: |
          docker-compose up -d --build  
      - name: Populate Yourls table from namespaces
        run: |
          cp -R namespaces/ ./build/namespaces/
          docker build -t build_yourls_uploader ./build/
          docker run --rm --network=pidsgeoconnexus_yourls_host --name build_yourls -v /sitemap:/sitemap -e "YOURLS_DB_PASS=arootpassword" build_yourls_uploader
      - name: Dump data
        run: |
          docker exec pidsgeoconnexus_mysql_1 sh -c "mysqldump -u root --password=arootpassword --add-drop-database -A | gzip > /docker-entrypoint-initdb.d/yourls.sql.gz"
          cp -R /sitemap ./sitemap
          mkdir backup
          cp ./mysql/yourls.sql.gz ./backup/yourls.sql.gz
      - name: Push sitemap to geoconnex.us
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'sitemap'
          destination_repo: 'webb-ben/geoconnex.us'
          destination_branch: 'dev'
          user_email: 'benjamin.miller.webb@gmail.com'
          user_name: 'webb-ben'
      - name: Push backup to geoconnex.us
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'backup'
          destination_repo: 'webb-ben/geoconnex.us'
          destination_branch: 'dev'
          user_email: 'benjamin.miller.webb@gmail.com'
          user_name: 'webb-ben'
